let AvailableShafts = [
  // Tour/Tour FLT
  {
    shaft_name: "Tour 110",
    material: "STEEL",
    swing_speed: "74-79",
    swing_speed_min: 74,
    swing_speed_max: 79,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "MID",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "TOUR",
    count: 0,
  },
  {
    shaft_name: "Tour 115",
    material: "STEEL",
    swing_speed: "80-85",
    swing_speed_min: 80,
    swing_speed_max: 85,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "MID",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "TOUR",
    count: 0,
  },
  {
    shaft_name: "Tour 120",
    material: "STEEL",
    swing_speed: "85-90",
    swing_speed_min: 85,
    swing_speed_max: 90,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "MID",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "TOUR",
    count: 0,
  },
  // {
  //   shaft_name: "Tour 125",
  //   material: "STEEL",
  //   swing_speed: "90-95",
  //   tempo: "SMOOTH",
  //   relese: "EARLY",
  //   trajectory: "MID",
  //   spin: "HIGH",
  //   distance_control: "DISTANCE",
  //   weight: "HEAVY",
  //   count: 0,
  // },
  {
    shaft_name: "Tour 125",
    material: "STEEL",
    swing_speed: "90-95",
    swing_speed_min: 90,
    swing_speed_max: 95,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "MID",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "HEAVY",
    count: 0,
  },
  {
    shaft_name: "Tour 130",
    material: "STEEL",
    swing_speed: "95-110",
    swing_speed_min: 95,
    swing_speed_max: 110,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "MID",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "HEAVY",
    count: 0,
  },
  //   C-Taper
  {
    shaft_name: "C-Taper 110",
    material: "STEEL",
    swing_speed: "74-79",
    swing_speed_min: 74,
    swing_speed_max: 79,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "LOW",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "TOUR",
    count: 0,
  },
  {
    shaft_name: "C-Taper 115",
    material: "STEEL",
    swing_speed: "80-85",
    swing_speed_min: 80,
    swing_speed_max: 79,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "LOW",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "TOUR",
    count: 0,
  },
  {
    shaft_name: "C-Taper 120",
    material: "STEEL",
    swing_speed: "85-90",
    swing_speed_min: 85,
    swing_speed_max: 90,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "LOW",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "TOUR",
    count: 0,
  },
  {
    shaft_name: "C-Taper 125",
    material: "STEEL",
    swing_speed: "90-95",
    swing_speed_min: 90,
    swing_speed_max: 95,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "LOW",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "HEAVY",
    count: 0,
  },
  {
    shaft_name: "C-Taper 130",
    material: "STEEL",
    swing_speed: "95-110",
    swing_speed_min: 95,
    swing_speed_max: 110,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "LOW",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "HEAVY",
    count: 0,
  },
  //   $-Taper
  {
    shaft_name: "$-taper 110",
    material: "STEEL",
    swing_speed: "74-79",
    swing_speed_min: 74,
    swing_speed_max: 79,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "MID",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "TOUR",
    count: 0,
  },
  {
    shaft_name: "$-taper 115",
    material: "STEEL",
    swing_speed: "80-85",
    swing_speed_min: 80,
    swing_speed_max: 85,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "MID",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "TOUR",
    count: 0,
  },
  {
    shaft_name: "$-taper 120",
    material: "STEEL",
    swing_speed: "85-90",
    swing_speed_min: 85,
    swing_speed_max: 90,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "MID",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "TOUR",
    count: 0,
  },
  {
    shaft_name: "$-taper 125",
    material: "STEEL",
    swing_speed: "90-95",
    swing_speed_min: 90,
    swing_speed_max: 95,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "MID",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "HEAVY",
    count: 0,
  },
  {
    shaft_name: "$-taper 130",
    material: "STEEL",
    swing_speed: "95-110",
    swing_speed_min: 95,
    swing_speed_max: 110,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "MID",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "HEAVY",
    count: 0,
  },
  //   Tour V
  {
    shaft_name: "Tour V 125",
    material: "STEEL",
    swing_speed: "90-95",
    swing_speed_min: 90,
    swing_speed_max: 95,
    tempo: "SMOOTH",
    relese: "LATE",
    trajectory: "MID",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "HEAVY",
    count: 0,
  },
  {
    shaft_name: "Tour V 130",
    material: "STEEL",
    swing_speed: "95-110",
    swing_speed_min: 95,
    swing_speed_max: 110,
    tempo: "SMOOTH",
    relese: "LATE",
    trajectory: "MID",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "HEAVY",
    count: 0,
  },

  {
    shaft_name: "Tour V 100",
    material: "STEEL",
    swing_speed: "70-80",
    swing_speed_min: 70,
    swing_speed_max: 80,
    tempo: "SMOOTH",
    relese: "LATE",
    trajectory: "MID",
    spin: "LOW",
    distance_control: "DISTANCE/CONTROL",
    weight: "MID",
    count: 0,
  },

  {
    shaft_name: "Tour V 110",
    material: "STEEL",
    swing_speed: "80-90",
    swing_speed_min: 80,
    swing_speed_max: 90,
    tempo: "SMOOTH",
    relese: "LATE",
    trajectory: "MID",
    spin: "LOW",
    distance_control: "DISTANCE/CONTROL",
    weight: "MID",
    count: 0,
  },

  {
    shaft_name: "Tour V 120",
    material: "STEEL",
    swing_speed: "90-100",
    swing_speed_min: 90,
    swing_speed_max: 100,
    tempo: "SMOOTH",
    relese: "LATE",
    trajectory: "MID",
    spin: "LOW",
    distance_control: "DISTANCE/CONTROL",
    weight: "MID",
    count: 0,
  },
  //   C-Taper Lite
  {
    shaft_name: "C-Taper Lite 105",
    material: "STEEL",
    swing_speed: "70-80",
    swing_speed_min: 70,
    swing_speed_max: 80,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "HIGH",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "MID",
    count: 0,
  },
  {
    shaft_name: "C-Taper Lite 110",
    material: "STEEL",
    swing_speed: "80-90",
    swing_speed_min: 80,
    swing_speed_max: 90,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "HIGH",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "MID",
    count: 0,
  },
  {
    shaft_name: "C-Taper Lite 115",
    material: "STEEL",
    swing_speed: "90-100",
    swing_speed_min: 90,
    swing_speed_max: 100,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "HIGH",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "MID",
    count: 0,
  },

  //   $-Taper Lite

  {
    shaft_name: "$-Taper Lite 95",
    material: "STEEL",
    swing_speed: "70-75",
    swing_speed_min: 70,
    swing_speed_max: 75,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "HIGH",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "LITE",
    count: 0,
  },

  {
    shaft_name: "$-Taper Lite 100",
    material: "STEEL",
    swing_speed: "75-80",
    swing_speed_min: 75,
    swing_speed_max: 80,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "HIGH",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "LITE",
    count: 0,
  },

  {
    shaft_name: "$-Taper Lite 105",
    material: "STEEL",
    swing_speed: "80-85",
    swing_speed_min: 80,
    swing_speed_max: 85,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "HIGH",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "LITE",
    count: 0,
  },

  //   Tour Lite
  {
    shaft_name: "Tour Lite 95",
    material: "STEEL",
    swing_speed: "70-75",
    swing_speed_min: 70,
    swing_speed_max: 75,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "LITE",
    count: 0,
  },
  {
    shaft_name: "Tour Lite 100",
    material: "STEEL",
    swing_speed: "75-80",
    swing_speed_min: 75,
    swing_speed_max: 80,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "LITE",
    count: 0,
  },
  {
    shaft_name: "Tour Lite 105",
    material: "STEEL",
    swing_speed: "80-85",
    swing_speed_min: 80,
    swing_speed_max: 85,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "LITE",
    count: 0,
  },

  //   Max Steel
  {
    shaft_name: "Max Steel 80R",
    material: "STEEL",
    swing_speed: "65-70",
    swing_speed_min: 65,
    swing_speed_max: 70,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "ULTRA LITE",
    count: 0,
  },
  {
    shaft_name: "Max Steel 80S",
    material: "STEEL",
    swing_speed: "70-75",
    swing_speed_min: 70,
    swing_speed_max: 75,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "ULTRA LITE",
    count: 0,
  },
  {
    shaft_name: "Max Steel 80X",
    material: "STEEL",
    swing_speed: "75-80",
    swing_speed_min: 75,
    swing_speed_max: 80,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "ULTRA LITE",
    count: 0,
  },
  //   TGI
  {
    shaft_name: "TGI 50",
    material: "Graphite",
    swing_speed: "40-65",
    swing_speed_min: 40,
    swing_speed_max: 65,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "MID",
    spin: "MID",
    distance_control: "CONTROL",
    weight: "ULTRA LITE",
    count: 0,
  },
  {
    shaft_name: "TGI 60",
    material: "Graphite",
    swing_speed: "65-70",
    swing_speed_min: 65,
    swing_speed_max: 80,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "MID",
    spin: "MID",
    distance_control: "CONTROL",
    weight: "ULTRA LITE",
    count: 0,
  },
  {
    shaft_name: "TGI 70",
    material: "Graphite",
    swing_speed: "70-75",
    swing_speed_min: 70,
    swing_speed_max: 75,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "MID",
    spin: "MID",
    distance_control: "CONTROL",
    weight: "LITE",
    count: 0,
  },
  {
    shaft_name: "TGI 80",
    material: "Graphite",
    swing_speed: "75-80",
    swing_speed_min: 75,
    swing_speed_max: 80,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "MID",
    spin: "MID",
    distance_control: "CONTROL",
    weight: "LITE",
    count: 0,
  },
  {
    shaft_name: "TGI 90",
    material: "Graphite",
    swing_speed: "80-85",
    swing_speed_min: 80,
    swing_speed_max: 85,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "MID",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "MID",
    count: 0,
  },
  {
    shaft_name: "TGI 95",
    material: "Graphite",
    swing_speed: "85-90",
    swing_speed_min: 85,
    swing_speed_max: 90,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "MID",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "MID",
    count: 0,
  },
  {
    shaft_name: "TGI 100",
    material: "Graphite",
    swing_speed: "90-95",
    swing_speed_min: 90,
    swing_speed_max: 95,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "MID",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "MID",
    count: 0,
  },
  {
    shaft_name: "TGI 110",
    material: "Graphite",
    swing_speed: "95-100",
    swing_speed_min: 95,
    swing_speed_max: 100,
    tempo: "QUICK",
    relese: "LATE",
    trajectory: "MID",
    spin: "LOW",
    distance_control: "CONTROL",
    weight: "TOUR",
    count: 0,
  },

  //   Pgi
  {
    shaft_name: "PGI 60",
    material: "Graphite",
    swing_speed: "65-70",
    swing_speed_min: 65,
    swing_speed_max: 70,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "HIGH",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "ULTRA LITE",
    count: 0,
  },
  {
    shaft_name: "PGI 70",
    material: "Graphite",
    swing_speed: "70-75",
    swing_speed_min: 70,
    swing_speed_max: 75,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "HIGH",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "LITE",
    count: 0,
  },
  {
    shaft_name: "PGI 80",
    material: "Graphite",
    swing_speed: "75-80",
    swing_speed_min: 75,
    swing_speed_max: 80,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "HIGH",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "LITE",
    count: 0,
  },
  {
    shaft_name: "PGI 90",
    material: "Graphite",
    swing_speed: "85-90",
    swing_speed_min: 85,
    swing_speed_max: 90,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "HIGH",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "MID",
    count: 0,
  },
  {
    shaft_name: "PGI 100",
    material: "Graphite",
    swing_speed: "90-95",
    swing_speed_min: 90,
    swing_speed_max: 95,
    tempo: "MODERATE",
    relese: "MID",
    trajectory: "HIGH",
    spin: "MID",
    distance_control: "DISTANCE/CONTROL",
    weight: "MID",
    count: 0,
  },

  //   Max
  {
    shaft_name: "Max 45",
    material: "Graphite",
    swing_speed: "40-60",
    swing_speed_min: 40,
    swing_speed_max: 60,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "ULTRA LITE",
    count: 0,
  },

  {
    shaft_name: "Max 55",
    material: "Graphite",
    swing_speed: "60-65",
    swing_speed_min: 60,
    swing_speed_max: 65,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "ULTRA LITE",
    count: 0,
  },
  {
    shaft_name: "Max 65",
    material: "Graphite",
    swing_speed: "65-70",
    swing_speed_min: 65,
    swing_speed_max: 70,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "ULTRA LITE",
    count: 0,
  },

  {
    shaft_name: "Max 75",
    material: "Graphite",
    swing_speed: "70-75",
    swing_speed_min: 70,
    swing_speed_max: 75,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "LITE",
    count: 0,
  },
  {
    shaft_name: "Max 85",
    material: "Graphite",
    swing_speed: "75-80",
    swing_speed_min: 75,
    swing_speed_max: 80,
    tempo: "SMOOTH",
    relese: "EARLY",
    trajectory: "HIGH",
    spin: "HIGH",
    distance_control: "DISTANCE",
    weight: "LITE",
    count: 0,
  },
];
